import { 
  Zone, 
  Gate, 
  EmergencyExit, 
  ResponseTeam, 
  AmbulanceUnit, 
  Incident, 
  ParkingArea, 
  SystemTelemetry, 
  ValidationMetric,
  SimulatorFeedback 
} from './types';

export const INITIAL_TELEMETRY: SystemTelemetry = {
  eventName: "Independence Day Public Gathering & NCC Parade",
  location: "Demo Ground - Sector A / Pavilion Arena",
  totalAttendees: 12480,
  peakCapacity: 18000,
  activeIncidentsCount: 4,
  criticalZonesCount: 2,
  deployedTeamsCount: 5,
  availableAmbulancesCount: 3,
  networkStatus: "ONLINE",
  lastTelemetryUpdate: "Just now",
  systemHealth: "OPERATIONAL",
};

export const INITIAL_ZONES: Zone[] = [
  {
    id: "A",
    name: "Zone A (North Entry Plaza)",
    capacity: 3500,
    currentCount: 1820,
    density: 1.8, // ppl/m^2
    densityGrowthRate: 2.1,
    flowDirection: "SOUTH",
    flowSpeed: 1.1,
    inflowRate: 95,
    outflowRate: 90,
    riskScore: 22,
    riskLevel: "LOW",
    confidenceScore: 92,
    confidenceLevel: "HIGH",
    nearbyGates: ["Gate 1"],
    nearbyExits: ["E1"],
    assignedTeams: ["TEAM-CHARLIE"],
    activeIncidentIds: [],
    reasons: ["Smooth linear progression through Gate 1", "Wide corridor with unhindered dispersal"],
    evidenceConfidence: {
      density: "HIGH",
      flow: "HIGH",
      exitStatus: "HIGH",
      incidentReports: "HIGH",
    },
    coordinates: { x: 50, y: 30, width: 260, height: 160 },
  },
  {
    id: "B",
    name: "Zone B (Grandstand Stage Concourse)",
    capacity: 4000,
    currentCount: 2450,
    density: 2.7,
    densityGrowthRate: 4.8,
    flowDirection: "EAST",
    flowSpeed: 0.9,
    inflowRate: 110,
    outflowRate: 95,
    riskScore: 42,
    riskLevel: "MODERATE",
    confidenceScore: 88,
    confidenceLevel: "HIGH",
    nearbyGates: ["Gate 2"],
    nearbyExits: ["E1"],
    assignedTeams: ["TEAM-DELTA"],
    activeIncidentIds: ["DX-0039"],
    reasons: ["Steady audience gathering near primary VIP stage", "Minor slowing near central walkway"],
    evidenceConfidence: {
      density: "HIGH",
      flow: "HIGH",
      exitStatus: "HIGH",
      incidentReports: "HIGH",
    },
    coordinates: { x: 350, y: 30, width: 280, height: 160 },
  },
  {
    id: "C",
    name: "Zone C (Central Festival Junction)",
    capacity: 3000,
    currentCount: 3120,
    density: 4.9, // high dangerous density
    densityGrowthRate: 18.4,
    flowDirection: "COUNTER_FLOW",
    flowSpeed: 0.3,
    inflowRate: 185,
    outflowRate: 65,
    riskScore: 84,
    riskLevel: "CRITICAL",
    confidenceScore: 78,
    confidenceLevel: "MEDIUM",
    nearbyGates: ["Gate 3"],
    nearbyExits: ["E2"],
    assignedTeams: [],
    activeIncidentIds: ["DX-0042", "DX-0043"],
    reasons: [
      "+ High localized density (4.9 ppl/m² vs 3.0 safe limit)",
      "+ Rapid inflow increase via Gate 3 (+18.4% / 5m)",
      "+ Opposing movement vectors creating severe counter-flow",
      "+ Gate 3 junction acting as severe bottleneck",
      "+ Exit E2 partially constrained by temporary perimeter stall",
    ],
    evidenceConfidence: {
      density: "HIGH",
      flow: "MEDIUM",
      exitStatus: "LOW",
      incidentReports: "HIGH",
    },
    coordinates: { x: 50, y: 220, width: 260, height: 180 },
  },
  {
    id: "D",
    name: "Zone D (East Corridor & Food Court)",
    capacity: 2800,
    currentCount: 2280,
    density: 3.6,
    densityGrowthRate: 9.2,
    flowDirection: "CONVERGING",
    flowSpeed: 0.6,
    inflowRate: 130,
    outflowRate: 85,
    riskScore: 68,
    riskLevel: "HIGH",
    confidenceScore: 84,
    confidenceLevel: "HIGH",
    nearbyGates: ["Gate 4"],
    nearbyExits: ["E2"],
    assignedTeams: ["TEAM-ALPHA"],
    activeIncidentIds: ["DX-0041"],
    reasons: [
      "+ Elevated crowd concentration spillover from Zone C",
      "+ Inflow rate exceeds exit discharge rate",
      "+ Concurrence of queueing near refreshment pavilions",
    ],
    evidenceConfidence: {
      density: "HIGH",
      flow: "HIGH",
      exitStatus: "MEDIUM",
      incidentReports: "HIGH",
    },
    coordinates: { x: 350, y: 220, width: 280, height: 180 },
  },
  {
    id: "E",
    name: "Zone E (Southwest Dispersal Grounds)",
    capacity: 3500,
    currentCount: 1410,
    density: 1.4,
    densityGrowthRate: -1.2,
    flowDirection: "WEST",
    flowSpeed: 1.3,
    inflowRate: 60,
    outflowRate: 95,
    riskScore: 18,
    riskLevel: "LOW",
    confidenceScore: 94,
    confidenceLevel: "HIGH",
    nearbyGates: ["Gate 5"],
    nearbyExits: ["E3"],
    assignedTeams: ["TEAM-BRAVO"],
    activeIncidentIds: [],
    reasons: ["Optimal throughput toward Gate 5 open avenue", "Ample buffer space available for crowd redistribution"],
    evidenceConfidence: {
      density: "HIGH",
      flow: "HIGH",
      exitStatus: "HIGH",
      incidentReports: "HIGH",
    },
    coordinates: { x: 50, y: 430, width: 260, height: 150 },
  },
  {
    id: "F",
    name: "Zone F (South Transit & Parking Terminal)",
    capacity: 3200,
    currentCount: 1400,
    density: 1.5,
    densityGrowthRate: 1.0,
    flowDirection: "SOUTH",
    flowSpeed: 1.2,
    inflowRate: 75,
    outflowRate: 80,
    riskScore: 24,
    riskLevel: "LOW",
    confidenceScore: 90,
    confidenceLevel: "HIGH",
    nearbyGates: ["Gate 5"],
    nearbyExits: ["E3"],
    assignedTeams: [],
    activeIncidentIds: [],
    reasons: ["Smooth shuttle bus boarding flow", "No pedestrian congestion at terminal bays"],
    evidenceConfidence: {
      density: "HIGH",
      flow: "HIGH",
      exitStatus: "HIGH",
      incidentReports: "HIGH",
    },
    coordinates: { x: 350, y: 430, width: 280, height: 150 },
  },
];

export const INITIAL_GATES: Gate[] = [
  { id: "G1", name: "Gate 1 (North Main Entrance)", status: "OPEN", inflowRate: 95, capacityRate: 150, throttlePercent: 0, connectedZoneId: "A", isCongested: false },
  { id: "G2", name: "Gate 2 (VIP / Stage Ingress)", status: "REGULATED", inflowRate: 110, capacityRate: 140, throttlePercent: 20, connectedZoneId: "B", isCongested: false },
  { id: "G3", name: "Gate 3 (Central Fast-Pass Entry)", status: "OPEN", inflowRate: 185, capacityRate: 150, throttlePercent: 0, connectedZoneId: "C", isCongested: true },
  { id: "G4", name: "Gate 4 (East Commercial Gate)", status: "REGULATED", inflowRate: 130, capacityRate: 140, throttlePercent: 15, connectedZoneId: "D", isCongested: false },
  { id: "G5", name: "Gate 5 (South High-Capacity Exit/Entry)", status: "OPEN", inflowRate: 60, capacityRate: 260, throttlePercent: 0, connectedZoneId: "E", isCongested: false },
];

export const INITIAL_EXITS: EmergencyExit[] = [
  { id: "E1", name: "Exit E1 (North Evacuation Corridor)", status: "CLEAR", widthMeters: 6.0, flowThroughput: 300, connectedZoneId: "A" },
  { id: "E2", name: "Exit E2 (Central Auxiliary Gate)", status: "PARTIALLY_BLOCKED", widthMeters: 4.5, flowThroughput: 120, connectedZoneId: "C", obstructionReason: "Vendor cart & barricade misalignment" },
  { id: "E3", name: "Exit E3 (South Perimeter Boulevard)", status: "CLEAR", widthMeters: 8.0, flowThroughput: 450, connectedZoneId: "E" },
];

export const INITIAL_RESPONSE_TEAMS: ResponseTeam[] = [
  {
    id: "ALPHA",
    name: "Team Alpha (NCC Rapid Regulation)",
    leader: "Cadet Capt. S. Raman",
    personnelCount: 12,
    status: "DEPLOYED",
    currentLocationZone: "D",
    assignedIncidentId: "DX-0041",
    etaMinutes: 2,
    coverageZones: ["C", "D"],
    specialization: "CROWD_REGULATION",
    contactRadio: "CH-01 (462.562 MHz)",
  },
  {
    id: "BRAVO",
    name: "Team Bravo (Sector Marshals)",
    leader: "Under Officer K. Gowda",
    personnelCount: 10,
    status: "AVAILABLE",
    currentLocationZone: "E",
    assignedIncidentId: null,
    etaMinutes: null,
    coverageZones: ["E", "F"],
    specialization: "EVACUATION_ESCORT",
    contactRadio: "CH-02 (462.587 MHz)",
  },
  {
    id: "CHARLIE",
    name: "Team Charlie (North Perimeter Unit)",
    leader: "Sgt. Anita Desai",
    personnelCount: 8,
    status: "DEPLOYED",
    currentLocationZone: "A",
    assignedIncidentId: null,
    etaMinutes: 4,
    coverageZones: ["A", "B"],
    specialization: "PERIMETER_CONTROL",
    contactRadio: "CH-03 (462.612 MHz)",
  },
  {
    id: "DELTA",
    name: "Team Delta (First Response Support)",
    leader: "Cpl. V. Kumar",
    personnelCount: 8,
    status: "AVAILABLE",
    currentLocationZone: "B",
    assignedIncidentId: null,
    etaMinutes: null,
    coverageZones: ["B", "C"],
    specialization: "MEDICAL_FIRST_AID",
    contactRadio: "CH-04 (462.637 MHz)",
  },
];

export const INITIAL_AMBULANCES: AmbulanceUnit[] = [
  { id: "AMB-01", callSign: "Ambulance Lifeline-1", status: "STANDBY", assignedZone: "North Bay (Zone A)", driver: "R. Sharma", paramedic: "Dr. Meera N", eta: "Immediate", equipmentLevel: "ADVANCED_LIFE_SUPPORT" },
  { id: "AMB-02", callSign: "Ambulance Lifeline-2", status: "STANDBY", assignedZone: "Central Bay (Zone C)", driver: "T. Joseph", paramedic: "Staff Nurse Arun", eta: "Immediate", equipmentLevel: "BASIC" },
  { id: "AMB-03", callSign: "Ambulance Lifeline-3", status: "STANDBY", assignedZone: "South Bay (Zone F)", driver: "M. Patil", paramedic: "Dr. S. Kulkarni", eta: "Immediate", equipmentLevel: "ADVANCED_LIFE_SUPPORT" },
];

export const INITIAL_PARKING: ParkingArea[] = [
  { id: "P1", name: "Parking P1 (North General Lot)", capacity: 1200, currentOccupancy: 984, occupancyPercent: 82, status: "NORMAL", spilloverRiskToPedestrians: "LOW", connectedZone: "A" },
  { id: "P2", name: "Parking P2 (East Pavilion Lot)", capacity: 1500, currentOccupancy: 1440, occupancyPercent: 96, status: "CRITICAL_FULL", spilloverRiskToPedestrians: "HIGH", connectedZone: "D" },
  { id: "P3", name: "Parking P3 (South Express Bus Bay)", capacity: 800, currentOccupancy: 344, occupancyPercent: 43, status: "NORMAL", spilloverRiskToPedestrians: "LOW", connectedZone: "F" },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: "DX-0042",
    zoneId: "C",
    timestamp: "14:32:10",
    type: "CROWD_COMPRESSION",
    severity: "CRITICAL",
    status: "REPORTED",
    title: "High Compression Alert near Gate 3 Ingress",
    description: "Pedestrian density has surged to 4.9 ppl/m². Inflow from Gate 3 (185 ppl/min) greatly exceeds clearance rate (65 ppl/min). Physical crowd friction and compression detected.",
    evidence: [
      "Visual density sensor: 4.9 ppl/m² (Severe)",
      "Counter-flow detected between incoming visitors and food pavilion egress",
      "Reduced outflow velocity to 0.3 m/s",
    ],
    recommendedResponse: [
      "Review and throttle Gate 3 inflow by 40-60%",
      "Open auxiliary avenue toward Gate 5 / Exit E3",
      "Deploy Team Alpha or Bravo for directional barrier guidance",
      "Broadcast safe redirection announcement on South PA system",
    ],
    assignedTeamId: null,
    humanVerified: false,
    operatorNotes: "",
    createdAt: "2026-08-30T14:32:10Z",
    updatedAt: "2026-08-30T14:32:10Z",
  },
  {
    id: "DX-0043",
    zoneId: "C",
    timestamp: "14:30:45",
    type: "EXIT_OBSTRUCTION",
    severity: "HIGH",
    status: "VERIFIED",
    title: "Partial Obstruction Reported at Exit E2",
    description: "Auxiliary egress E2 throughput reduced by ~60% due to an unapproved refreshment pushcart and misaligned portable crowd barricades.",
    evidence: [
      "Throughput reduction from 300 to 120 ppl/min",
      "Visual check confirmed by sector marshal #14",
    ],
    recommendedResponse: [
      "Deploy marshal to clear stall and reset barricades to 45-degree diversion angle",
    ],
    assignedTeamId: null,
    humanVerified: true,
    operatorNotes: "Marshal dispatched to confirm clearance path.",
    createdAt: "2026-08-30T14:30:45Z",
    updatedAt: "2026-08-30T14:31:00Z",
  },
  {
    id: "DX-0041",
    zoneId: "D",
    timestamp: "14:28:15",
    type: "BOTTLENECK_PINCH",
    severity: "HIGH",
    status: "MITIGATING",
    title: "Concourse Convergence Queue Spillover",
    description: "East Corridor pedestrian flow converging at sharp 90-degree corner near Food Pavilion. Team Alpha is on site deploying snake-queue tape.",
    evidence: [
      "Density at 3.6 ppl/m²",
      "P2 parking spillover adding vehicle-to-pedestrian queue friction",
    ],
    recommendedResponse: [
      "Maintain active snake-queue pacing",
      "Coordinate with P2 traffic marshal for vehicle diversion",
    ],
    assignedTeamId: "ALPHA",
    humanVerified: true,
    operatorNotes: "Team Alpha actively guiding pedestrian queue.",
    createdAt: "2026-08-30T14:28:15Z",
    updatedAt: "2026-08-30T14:29:30Z",
  },
  {
    id: "DX-0039",
    zoneId: "B",
    timestamp: "14:15:00",
    type: "COUNTER_FLOW_CONFLICT",
    severity: "MEDIUM",
    status: "VERIFIED",
    title: "Audience Stage Transition Swirl",
    description: "Attendees moving between Zone A and Zone B causing temporary micro-eddies in front of Grandstand Stage walkway.",
    evidence: [
      "Localized flow vectors opposing each other by 140 degrees",
    ],
    recommendedResponse: [
      "Regulate Gate 2 incoming batches with 30-second interval spacing",
    ],
    assignedTeamId: "DELTA",
    humanVerified: true,
    operatorNotes: "Team Delta managing one-way lane ropes.",
    createdAt: "2026-08-30T14:15:00Z",
    updatedAt: "2026-08-30T14:20:00Z",
  },
];

export const INITIAL_AUDIT_LOG = [
  {
    id: "AUD-8921",
    timestamp: "14:32:15",
    operatorId: "KA2025SDIA2540816",
    operatorName: "Cadet Officer Pavan C N",
    actionType: "INTERVENTION_REVIEW" as const,
    details: "System generated Risk Escalation Alert for Zone C (Score 84/100). Counterfactual simulator launched.",
    targetEntity: "Zone C / Gate 3",
    decisionContext: "Reviewing What-If Scenarios A, B, and C to relieve Gate 3 bottleneck without overwhelming Zone D.",
    hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  },
  {
    id: "AUD-8920",
    timestamp: "14:28:30",
    operatorId: "KA2025SDIA2540816",
    operatorName: "Cadet Officer Pavan C N",
    actionType: "TEAM_ASSIGN" as const,
    details: "Assigned Team Alpha to Incident DX-0041 in Zone D for queue snake-pacing.",
    targetEntity: "Team Alpha -> Zone D",
    decisionContext: "Human verified bottleneck near food pavilion concourse.",
    hash: "4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
  },
  {
    id: "AUD-8919",
    timestamp: "14:20:10",
    operatorId: "KA2025SDIA2540816",
    operatorName: "Cadet Officer Pavan C N",
    actionType: "GATE_OVERRIDE" as const,
    details: "Adjusted Gate 2 throttle to 20% to prevent stage concourse overcrowding.",
    targetEntity: "Gate 2",
    decisionContext: "Precautionary flow smoothing during VIP parade segment.",
    hash: "ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d",
  },
];

export const VALIDATION_TARGETS: ValidationMetric[] = [
  {
    id: "VAL-01",
    category: "Risk Classification",
    metricName: "Zone Risk Classification Accuracy",
    targetValue: "> 92.0% Agreement",
    currentSimulatedBenchmark: "94.6% (Synthetic Venue Corpus)",
    description: "Evaluates multi-factor risk categorization against expert safety inspector baseline reviews.",
    status: "MEETS_TARGET",
  },
  {
    id: "VAL-02",
    category: "False Alerts",
    metricName: "Critical False Positive Rate",
    targetValue: "< 4.5%",
    currentSimulatedBenchmark: "3.2% in controlled test simulations",
    description: "Prevents alarm fatigue by requiring multi-modal evidence concurrence before triggering red escalation.",
    status: "MEETS_TARGET",
  },
  {
    id: "VAL-03",
    category: "Latency",
    metricName: "Risk Escalation Detection Latency",
    targetValue: "< 3.0 seconds",
    currentSimulatedBenchmark: "1.4 seconds edge computation",
    description: "Time elapsed from sensor telemetry surge to decision-support recommendation presentation.",
    status: "MEETS_TARGET",
  },
  {
    id: "VAL-04",
    category: "Simulation Fidelity",
    metricName: "Flow Estimation Mean Error",
    targetValue: "< 8.0%",
    currentSimulatedBenchmark: "6.1% relative error",
    description: "Discrepancy between simulated pedestrian redistribution and hydrodynamic flow validation models.",
    status: "MEETS_TARGET",
  },
  {
    id: "VAL-05",
    category: "Intervention Quality",
    metricName: "Scenario Ranking Agreement with Safety SOPs",
    targetValue: "> 88.0%",
    currentSimulatedBenchmark: "91.2% concordance",
    description: "Measures whether AI-recommended best scenario matches trained disaster management commander rankings.",
    status: "MEETS_TARGET",
  },
  {
    id: "VAL-06",
    category: "Human Decision Time",
    metricName: "Operator Incident Decision Time",
    targetValue: "< 45 seconds",
    currentSimulatedBenchmark: "24.5 seconds average",
    description: "Time taken by command officer to evaluate trade-offs and approve structured intervention.",
    status: "MEETS_TARGET",
  },
];

export const RISK_FORMULA_WEIGHTS = {
  densityWeight: 0.25,
  flowImbalanceWeight: 0.20,
  compressionRateWeight: 0.20,
  exitConstraintWeight: 0.15,
  incidentSeverityWeight: 0.10,
  responseTeamCoverageWeight: 0.10,
};

export const INITIAL_SIMULATOR_FEEDBACK: SimulatorFeedback[] = [
  {
    id: "SFB-101",
    scenarioId: "SCENARIO-A",
    scenarioName: "Strategy Alpha (Balanced Regulation & Divert)",
    timestamp: "20:45:10",
    vote: "UP",
    utilityRating: 5,
    accuracyRating: 5,
    tags: ["Realistic crowd flow", "Clear trade-offs", "Balanced risk distribution"],
    comments: "Opening Gate 5 early accurately modeled the downstream pressure drop in Zone C.",
    operator: "Cadet Officer Pavan C N (NCC)"
  },
  {
    id: "SFB-102",
    scenarioId: "SCENARIO-B",
    scenarioName: "Strategy Bravo (Rapid Gate 3 Full Lockdown)",
    timestamp: "20:52:33",
    vote: "DOWN",
    utilityRating: 4,
    accuracyRating: 4,
    tags: ["Severe secondary bottleneck", "Accurate warning indicators"],
    comments: "Correctly flagged that slamming Gate 3 shut without opening Exit E2 creates critical surge.",
    operator: "Duty Officer (Sector A)"
  }
];

export const JUDGE_FAQS = [
  {
    q: "Doesn't CCTV already detect crowds?",
    a: "Yes. Computer vision detection of density is established research. DRISHTI-X focuses on what happens *after* detection: identifying multi-factor causes, simulating counterfactual interventions (e.g. 'What if Gate 3 is closed vs Gate 5 opened?'), revealing downstream trade-offs, and giving commanders structured human-in-the-loop decision choices."
  },
  {
    q: "Why is Counterfactual Simulation your core innovation?",
    a: "In real crowd disasters, knee-jerk decisions like abruptly slamming a gate shut often transfer crushing pressure to an adjacent narrow exit. Counterfactual simulation allows the operator to test actions in virtual state first, discovering secondary congestion before giving physical orders."
  },
  {
    q: "Does DRISHTI-X take autonomous command actions?",
    a: "No. Strict Human-in-the-Loop design is a core principle. The AI acts exclusively as an analytical advisor providing uncertainty bounds, risk factors, and ranked scenario alternatives. Final operational approval remains with authorized human commanders."
  },
  {
    q: "How does the system handle uncertainty or missing sensors?",
    a: "Every assessment displays explicit confidence metrics (e.g. 78% confidence, breakdown by density, flow, and exit status). When data confidence is below threshold, it explicitly flags 'Human verification recommended' before allowing intervention dispatch."
  },
  {
    q: "How does privacy protection work?",
    a: "DRISHTI-X employs Privacy by Design. It does NOT perform facial recognition, individual tracking, biometric profiling, or weapon detection. All algorithms operate purely on aggregate crowd densities, directional velocity vectors, and zone occupancy counts."
  },
  {
    q: "What happens during a network outage or internet disconnection?",
    a: "DRISHTI-X features an Offline Safety Mode. The decision engine, simulation models, and audit logs continue running locally in-memory and in browser storage, ensuring command continuity without cloud dependency."
  }
];
